pull_request_rules:
  - name: Automatic merge when CI passes and PR is approved
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash


  # Automatic merging on trivial scala-steward PRs
  - name: automatic squash merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: squash
  - name: automatic squash merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: squash
  - name: automatic squash merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: squash
  - name: automatic squash merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: squash


  # Semi automatic merging if scala-steward PRs get more complex
  - name: semi-automatic merge for scala-steward pull requests
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
