name: Scalalint
baseurl: ''
description: A Scala linter based on Scalafix
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.4+2-19828565-SNAPSHOT
org: org.scalalint
markdown: kramdown
