name: Scalalint
baseurl: ''
description: A Scala linter based on Scalafix
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.2+2-b9a69207-SNAPSHOT
org: org.scalalint
markdown: kramdown
