name: Scalalint
baseurl: ''
description: A Scala linter based on Scalafix
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1+1-9edf5fae-SNAPSHOT
org: org.scalalint
markdown: kramdown
