addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.9.10")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.2.1")
addSbtPlugin("com.geirsson"      % "sbt-ci-release" % "1.4.31")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.3.0")
addSbtPlugin("com.47deg"         % "sbt-microsites" % "0.9.7")
