addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.9.15")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.3.4")
addSbtPlugin("com.geirsson"      % "sbt-ci-release" % "1.5.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.6.0")
addSbtPlugin("com.47deg"         % "sbt-microsites" % "1.2.0")
